import { useEffect } from "react";
import Head from "next/head";
import AOS from "aos";
import "aos/dist/aos.css";
import CarouselHero from "../component/group/Carousel-Hero";
import Navbar from "../component/group/Navbar";
import SwiperCategory from "../component/group/swipercategory";
import SwiperPengumuman from "../component/group/swiperPengumuman";
import Styles from "../styles/Home.module.css";
import Footer from "../component/group/Footer";
// import bgImage from "../public/Wallppaper-bg.jpeg";

export default function Home() {
  useEffect(() => {
    AOS.init({
      duration: 1000,
    });
    AOS.refresh();
  }, []);

  return (
    <div>
      <Head>
        <title>Probolinggo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <section className="mb-5" style={{ backgroundColor: "#0C0717" }}>
        <Navbar Berandas="actived" />
      </section>
      <section className="container mb-5">
        <div
          data-aos="fade-zoom-in"
          data-aos-easing="ease-in-back"
          data-aos-delay="300"
          data-aos-offset="0"
        >
          <CarouselHero />
        </div>
      </section>
      <div className={Styles.bgPengumuman}>
        <section className="container mt-3 mb-3 center">
          <h1
            data-aos="fade-zoom-in"
            data-aos-easing="ease-in-back"
            data-aos-delay="300"
            data-aos-offset="0"
            className={`mb-5 ${Styles.titlePengumuman}`}
          >
            Pengumuman
          </h1>
          <div
            data-aos="fade-zoom-in"
            data-aos-easing="ease-in-back"
            data-aos-delay="300"
            data-aos-offset="0"
          >
            <SwiperPengumuman />
          </div>
        </section>
      </div>
      <div>
        <section
          data-aos="fade-zoom-in"
          data-aos-easing="ease-in-back"
          data-aos-delay="300"
          data-aos-offset="0"
          className="pt-5"
        >
          <SwiperCategory
            title1="Pemerintahan"
            title2="Pendidikan"
            title3="Kesehatan"
            title4="Kemasyarakatan"
          />
        </section>
      </div>
      <footer>
        <Footer />
      </footer>
    </div>
  );
}
